### ISSUE TITLE
Unsound usages of unsafe implementation from `[u8]` to `__m128i`

### ISSUE THREAD

**Issue by llooFlashooll** [srijs/rust-crc32fast#41]
Hi, I am scanning the crc32fast in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/specialized/pclmulqdq.rs:198:35: 198:69
``` rust
unsafe fn get(a: &mut &[u8]) -> arch::__m128i {
    debug_assert!(a.len() >= 16);
    let r = arch::_mm_loadu_si128(a.as_ptr() as *const arch::__m128i);
    *a = &a[16..];
    return r;
}
```

This unsound implementation would create a misalignment issues. If the [u8] size is smaller than the __m128i, it would potentially lead to access out-of-bound in the memory.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by srijs** [comment]
Hi, thanks for the report!

I've double checked, and believe this is likely a false positive in from your tool. You mention two issues specifically:

1. Misalignment: The `_mm_loadu_si128` is a function specifically designed to perform unaligned loads from the memory address. As you can read [here in the docs](https://doc.rust-lang.org/stable/core/arch/x86_64/fn._mm_loadu_si128.html): "`mem_addr` does not need to be aligned on any particular boundary."

2. Out of bounds access: The function is marked `unsafe` specifically because the caller needs to ensure that `a` is at least 16 bytes long. The debug assert is not load bearing, instead you need to check for where `get` is called. There are three places where `get` is called, all of which ensure that the slice passed to it is at least 16 bytes long.

Happy to discuss and be convinced otherwise!
